USE [master]
GO

/****** Object:  Database [projekt]    Script Date: 15 sty 2020 17:06:25 ******/
CREATE DATABASE [projekt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projekt', FILENAME = N'F:\SQLServer2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\projekt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projekt_log', FILENAME = N'F:\SQLServer2017\MSSQL14.MSSQLSERVER\MSSQL\DATA\projekt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projekt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projekt] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projekt] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projekt] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projekt] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projekt] SET ARITHABORT OFF 
GO

ALTER DATABASE [projekt] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projekt] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projekt] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projekt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projekt] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projekt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projekt] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projekt] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projekt] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projekt] SET  DISABLE_BROKER 
GO

ALTER DATABASE [projekt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projekt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projekt] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projekt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projekt] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projekt] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projekt] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projekt] SET RECOVERY FULL 
GO

ALTER DATABASE [projekt] SET  MULTI_USER 
GO

ALTER DATABASE [projekt] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projekt] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projekt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projekt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projekt] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projekt] SET QUERY_STORE = OFF
GO

ALTER DATABASE [projekt] SET  READ_WRITE 
GO

